language: bash

services:
  - docker

script:
  - docker build . -t httpd
  - docker tag httpd corefantasy/httpd

deploy:
  provider: script
  script: bash dockerPush.sh
  on:
    branch: master

jobs:
  include:
    - stage: trigger downstream
      jdk: oraclejdk8
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
          sh trigger-travis.sh corefantasy ui $TRAVIS_ACCESS_TOKEN
        fi
